### ISSUE TITLE
version_everywhere.py

### ISSUE THREAD

**Issue by sridharankaliyamoorthy** [antiero/dotStudio#3]
Hi Antony Nasce,
Thanks a lot for wonderful handy tool :).
one more question ? is it possible to get versions difference between Two tracks? Fr example - If track 1 have v003 and Track 2 have v007. i just want to pick only diffrence versions. ? Because i need to export all the vfx shots to Davinci resolve. everytime i am exporting all the shots to davinci. i dont want to export the unchanged version shots.  plz help me.. TIA.

**Comment by antiero** [comment]
All possible with the Python API! 

The hardest part for you to work out will be the method of knowing "what's changed and since when?" - The last save? Since yesterday? What defines the different versions? What versioning system do you use? Does your timeline tie into a central database of which versions have been published/exported?

But I might be overcomplicating matters 😉

If you have a spec of how you'd like it to work feel free to message me :)

**Comment by sridharankay** [comment]
First of all i would like to thank you for ur immense response Anterio. :)  for giving me the positive hope. Since i am new to Hiero/Studio Scripting i initially stuck up with many things until i found ur amazing scripts. thanks a lot again.
My issue nw -
        to be able to define the difference which occured during "Max Version" function in Hiero/Studio and then export only those file whose version changed during "Max Version" process. With ur script i can update versions but i cant find which all are the shots only updated the versions. if you can help me out it would be great Anterio.

For Example - We need to export those files with new version. The idea is that we will run the script on specific track. The script will use "Max version" but it will also put copy of those shots which were changed to the new track. We can than easily select them, export i.e. for DaVinci and delete whole track after that.

Thanks In Advance. Looking foward to hearing from you Anterio. :+1:

**Comment by sridharankay** [comment]
Hi Anterio :) any upadate for my queries .
Thnx IA

**Comment by sridharankay** [comment]
Hi Anterio..

Any update fr my queries? Looking forward Man.

Thnx In Advance

**Comment by antiero** [comment]
Hey sridharankey, sorry for late reply. I don't have any updates for you at this time, but it's on my to-do list for the future! Have you tried messaging the nuke-user/hiero-user list to see if someone has already solved this problem? Cheers, Ant.

**Comment by sridharankay** [comment]
Hi Antireo. Thans fr ur response. Looking forward to hearing from you. U r scripts working perfectly when i updating Max versions. But i am facing little issue while using this scripts. i have attached the nuke Dialog box after using ur scripts.
![capture](https://cloud.githubusercontent.com/assets/18421685/15293801/e616c240-1b89-11e6-8396-4ad99872b30f.JPG)
in my Sequence only two shots i have actually updated but in the resulting dialog box its shows that for all the shots. Is it possible to get only updated shots lists.?? instead of All shots.

Thanks a lot anterio.

**Comment by sridharankay** [comment]
Hi antireo, really sorry to bother you again and again. i have tried to get help from forum,but it didnt work man. is there any  update from u?. looking forward to hear from you. it would be great if u can help me out with this.

Thanks a lot antireo.

**Comment by antiero** [comment]
Hi sridharankay, I'm afraid no updates for you. Pretty busy at the moment, but do keep reminding me! ;)

Have you had a chance to look into the hiero Python API Docs to get what you need from this plugin?

**Comment by sridharankay** [comment]
Hi antireo, really sorry to bother you again and again . Can you help me out to for getting difference in timeline? Is it possible to get only updated shots lists.?? instead of All shots. TIA

**Comment by antiero** [comment]
hi @sridharankay

Sadly, there is no simple 'out of the box' way to get a 'difference in timeline'.

If you can create a new Github issue, describing exactly how you'd like this to work in practice, I might be able to take a look, but the best thing to do is to learn more about the hiero.core Python API works, so that you can write exactly what you need.
